### ISSUE TITLE
Error and how do I access the recording wav file.

### ISSUE THREAD

**Issue by GayathriShrikanth** [danijel3/audio_gui#3]
File "C:\Users\gayat\Downloads\Flask_app-master\Flask_app-master\app.py", line 85, in audio
    proc = run(['ffprobe', '-of', 'default=noprint_wrappers=1', '/tmp/audio.wav'], text=True, stderr=PIPE)
  File "C:\Users\gayat\AppData\Local\Programs\Python\Python36\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'text'

This is the error I am getting. Any idea why it is so

**Comment by danijel3** [comment]
The `text` attribute was added in Python 3.7.  You can simply remove it or better yet replace that command with something meaningful. That's just a demonstration.
